rm /home/storage0/users/zhangxy/CraterII+3sig//output/boundmass.txt
rm /home/storage0/users/zhangxy/CraterII+3sig//output/dataProfile/*
nohup ./modRS /home/storage0/users/zhangxy/CraterII+3sig//output snapshot 000 &
nohup ./modRS /home/storage0/users/zhangxy/CraterII+3sig//output snapshot 001 &
nohup ./modRS /home/storage0/users/zhangxy/CraterII+3sig//output snapshot 002 &
nohup ./modRS /home/storage0/users/zhangxy/CraterII+3sig//output snapshot 003 &
nohup ./modRS /home/storage0/users/zhangxy/CraterII+3sig//output snapshot 004 &
nohup ./modRS /home/storage0/users/zhangxy/CraterII+3sig//output snapshot 005 &
nohup ./modRS /home/storage0/users/zhangxy/CraterII+3sig//output snapshot 006 &
nohup ./modRS /home/storage0/users/zhangxy/CraterII+3sig//output snapshot 007 &
nohup ./modRS /home/storage0/users/zhangxy/CraterII+3sig//output snapshot 008 &
nohup ./modRS /home/storage0/users/zhangxy/CraterII+3sig//output snapshot 009 &
nohup ./modRS /home/storage0/users/zhangxy/CraterII+3sig//output snapshot 010 &
nohup ./modRS /home/storage0/users/zhangxy/CraterII+3sig//output snapshot 011 &
nohup ./modRS /home/storage0/users/zhangxy/CraterII+3sig//output snapshot 012 &
nohup ./modRS /home/storage0/users/zhangxy/CraterII+3sig//output snapshot 013 &
nohup ./modRS /home/storage0/users/zhangxy/CraterII+3sig//output snapshot 014 &
nohup ./modRS /home/storage0/users/zhangxy/CraterII+3sig//output snapshot 015 &
nohup ./modRS /home/storage0/users/zhangxy/CraterII+3sig//output snapshot 016 &
nohup ./modRS /home/storage0/users/zhangxy/CraterII+3sig//output snapshot 017 &
nohup ./modRS /home/storage0/users/zhangxy/CraterII+3sig//output snapshot 018 &
nohup ./modRS /home/storage0/users/zhangxy/CraterII+3sig//output snapshot 019 &
nohup ./modRS /home/storage0/users/zhangxy/CraterII+3sig//output snapshot 020 &
nohup ./modRS /home/storage0/users/zhangxy/CraterII+3sig//output snapshot 021 &
nohup ./modRS /home/storage0/users/zhangxy/CraterII+3sig//output snapshot 022 &
nohup ./modRS /home/storage0/users/zhangxy/CraterII+3sig//output snapshot 023 &
nohup ./modRS /home/storage0/users/zhangxy/CraterII+3sig//output snapshot 024 &
nohup ./modRS /home/storage0/users/zhangxy/CraterII+3sig//output snapshot 025 &
nohup ./modRS /home/storage0/users/zhangxy/CraterII+3sig//output snapshot 026 &
nohup ./modRS /home/storage0/users/zhangxy/CraterII+3sig//output snapshot 027 &
nohup ./modRS /home/storage0/users/zhangxy/CraterII+3sig//output snapshot 028 &
nohup ./modRS /home/storage0/users/zhangxy/CraterII+3sig//output snapshot 029 &
nohup ./modRS /home/storage0/users/zhangxy/CraterII+3sig//output snapshot 030 &
nohup ./modRS /home/storage0/users/zhangxy/CraterII+3sig//output snapshot 031 &
nohup ./modRS /home/storage0/users/zhangxy/CraterII+3sig//output snapshot 032 &
nohup ./modRS /home/storage0/users/zhangxy/CraterII+3sig//output snapshot 033 &
nohup ./modRS /home/storage0/users/zhangxy/CraterII+3sig//output snapshot 034 &
nohup ./modRS /home/storage0/users/zhangxy/CraterII+3sig//output snapshot 035 &
nohup ./modRS /home/storage0/users/zhangxy/CraterII+3sig//output snapshot 036 &
nohup ./modRS /home/storage0/users/zhangxy/CraterII+3sig//output snapshot 037 &
nohup ./modRS /home/storage0/users/zhangxy/CraterII+3sig//output snapshot 038 &
nohup ./modRS /home/storage0/users/zhangxy/CraterII+3sig//output snapshot 039 &
nohup ./modRS /home/storage0/users/zhangxy/CraterII+3sig//output snapshot 040 &
nohup ./modRS /home/storage0/users/zhangxy/CraterII+3sig//output snapshot 041 &
nohup ./modRS /home/storage0/users/zhangxy/CraterII+3sig//output snapshot 042 &
nohup ./modRS /home/storage0/users/zhangxy/CraterII+3sig//output snapshot 043 &
nohup ./modRS /home/storage0/users/zhangxy/CraterII+3sig//output snapshot 044 &
nohup ./modRS /home/storage0/users/zhangxy/CraterII+3sig//output snapshot 045 &
nohup ./modRS /home/storage0/users/zhangxy/CraterII+3sig//output snapshot 046 &
nohup ./modRS /home/storage0/users/zhangxy/CraterII+3sig//output snapshot 047 &
nohup ./modRS /home/storage0/users/zhangxy/CraterII+3sig//output snapshot 048 &
nohup ./modRS /home/storage0/users/zhangxy/CraterII+3sig//output snapshot 049 &
nohup ./modRS /home/storage0/users/zhangxy/CraterII+3sig//output snapshot 050 &
nohup ./modRS /home/storage0/users/zhangxy/CraterII+3sig//output snapshot 051 &
nohup ./modRS /home/storage0/users/zhangxy/CraterII+3sig//output snapshot 052 &
nohup ./modRS /home/storage0/users/zhangxy/CraterII+3sig//output snapshot 053 &
nohup ./modRS /home/storage0/users/zhangxy/CraterII+3sig//output snapshot 054 &
nohup ./modRS /home/storage0/users/zhangxy/CraterII+3sig//output snapshot 055 &
